# Generated by Django 6.0.5 on 2026-05-17 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_orden_itemorden'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('conjuntos', 'Conjuntos'), ('bralettes', 'Bralettes'), ('bombachas', 'Bombachas'), ('accesorios', 'Accesorios'), ('otros', 'Otros')], default='otros', max_length=50),
        ),
    ]
