# Generated by Django 6.0.5 on 2026-05-25 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0007_producto_destacado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('conjuntos armados', 'Conjuntos armados'), ('bralettes', 'Bralettes'), ('bombachas', 'Bombachas'), ('babydoll', 'Babydolls'), ('otros', 'Otros')], default='otros', max_length=50),
        ),
        migrations.CreateModel(
            name='ColorProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('imagen', models.ImageField(upload_to='productos/colores/')),
                ('stock', models.IntegerField(default=0)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colores', to='tienda.producto')),
            ],
        ),
        migrations.AddField(
            model_name='itemcarrito',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tienda.colorproducto'),
        ),
    ]
