# Generated by Django 6.0.5 on 2026-06-25 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0012_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemorden',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tienda.colorproducto'),
        ),
        migrations.AddField(
            model_name='itemorden',
            name='talle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tienda.talleproducto'),
        ),
        migrations.AddField(
            model_name='orden',
            name='estado',
            field=models.CharField(choices=[('en_proceso', 'En proceso'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='en_proceso', max_length=20),
        ),
    ]
