# Generated by Django 6.0.5 on 2026-05-20 00:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0005_opcionenvio'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='envio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tienda.opcionenvio'),
        ),
        migrations.AddField(
            model_name='orden',
            name='metodo_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('mercadopago', 'MercadoPago')], default='efectivo', max_length=20),
        ),
    ]
