# Generated by Django 6.0.5 on 2026-05-25 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0008_alter_producto_categoria_colorproducto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='imagen',
        ),
    ]
