# Generated by Django 6.0.5 on 2026-09-15 18:28

import django.db.models.deletion
import tienda.subscription_models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0015_codigopromocional_orden_codigo_promo_etc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia_publica', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('submission_key', models.UUIDField(editable=False, unique=True)),
                ('external_reference', models.CharField(default=tienda.subscription_models.subscription_reference, editable=False, max_length=64, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=30)),
                ('destino', models.CharField(max_length=20)),
                ('talle', models.CharField(max_length=20)),
                ('tipo_prenda', models.CharField(blank=True, max_length=20)),
                ('estilo', models.CharField(blank=True, max_length=20)),
                ('respuestas_snapshot', models.JSONField(default=dict)),
                ('terminos_aceptados', models.BooleanField(default=False)),
                ('terminos_aceptados_at', models.DateTimeField(blank=True, null=True)),
                ('terminos_url', models.URLField(max_length=500)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('activa', 'Activa'), ('pausada', 'Pausada'), ('cancelada', 'Cancelada'), ('error', 'Error')], db_index=True, default='pendiente', max_length=20)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=12)),
                ('moneda', models.CharField(max_length=3)),
                ('frecuencia', models.PositiveIntegerField(default=1)),
                ('frecuencia_tipo', models.CharField(default='months', max_length=10)),
                ('mp_preapproval_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('mp_plan_id', models.CharField(blank=True, max_length=100)),
                ('mp_estado', models.CharField(blank=True, max_length=40)),
                ('mp_actualizado_at', models.DateTimeField(blank=True, null=True)),
                ('proximo_cobro_at', models.DateTimeField(blank=True, null=True)),
                ('autorizado_at', models.DateTimeField(blank=True, null=True)),
                ('cancelado_at', models.DateTimeField(blank=True, null=True)),
                ('init_point', models.URLField(blank=True, max_length=1000)),
                ('checkout_estado', models.CharField(default='new', max_length=20)),
                ('checkout_intentado_at', models.DateTimeField(blank=True, null=True)),
                ('ultimo_error', models.CharField(blank=True, max_length=200)),
                ('ultimo_evento', models.CharField(blank=True, max_length=120)),
                ('ultimo_evento_at', models.DateTimeField(blank=True, null=True)),
                ('confirmation_email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('admin_email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Suscripción',
                'verbose_name_plural': 'Suscripciones',
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='EventoMercadoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=64, unique=True)),
                ('topico', models.CharField(max_length=60)),
                ('recurso_id', models.CharField(max_length=100)),
                ('accion', models.CharField(blank=True, max_length=100)),
                ('recibido_at', models.DateTimeField(auto_now_add=True)),
                ('procesado_at', models.DateTimeField(blank=True, null=True)),
                ('intentos', models.PositiveIntegerField(default=0)),
                ('proximo_intento_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.CharField(blank=True, max_length=200)),
                ('suscripcion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eventos', to='tienda.suscripcion')),
            ],
            options={
                'ordering': ['recibido_at'],
            },
        ),
        migrations.CreateModel(
            name='PagoSuscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mp_authorized_payment_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('mp_payment_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=12)),
                ('moneda', models.CharField(max_length=3)),
                ('estado', models.CharField(max_length=40)),
                ('estado_factura', models.CharField(blank=True, max_length=40)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('mp_actualizado_at', models.DateTimeField(blank=True, null=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('suscripcion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='tienda.suscripcion')),
            ],
            options={
                'ordering': ['-fecha', '-pk'],
                'constraints': [models.CheckConstraint(condition=models.Q(('mp_authorized_payment_id__isnull', False), ('mp_payment_id__isnull', False), _connector='OR'), name='subscription_payment_has_external_id')],
            },
        ),
        migrations.CreateModel(
            name='EmailSuscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('cliente', 'Cliente'), ('admin', 'Administrador')], max_length=10)),
                ('payload', models.JSONField(default=dict)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('primer_intento_at', models.DateTimeField(blank=True, null=True)),
                ('enviado_at', models.DateTimeField(blank=True, null=True)),
                ('proximo_intento_at', models.DateTimeField(blank=True, null=True)),
                ('intentos', models.PositiveIntegerField(default=0)),
                ('proveedor_id', models.CharField(blank=True, max_length=100)),
                ('error', models.CharField(blank=True, max_length=200)),
                ('revision_manual', models.BooleanField(default=False)),
                ('suscripcion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emails', to='tienda.suscripcion')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('suscripcion', 'tipo'), name='unique_subscription_welcome_recipient')],
            },
        ),
    ]
