# Generated by Django 6.0.5 on 2026-09-30 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0016_suscripcion_eventomercadopago_pagosuscripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('conjuntos armados', 'Conjuntos armados'), ('bralettes', 'Bralettes'), ('bombachas', 'Bombachas'), ('babydoll', 'Babydolls'), ('otros', 'Otros'), ('ropa-deportiva', 'Ropa deportiva')], default='otros', max_length=50),
        ),
    ]
